const prisma = require("../../config/prisma");
const { analyzeJavaScript } = require("../lint/eslint.service");
const { reviewCode } = require("../ai/gemini.service");

/**
 * Normalizes variations in AI JSON fields down to schema specifications safely
 */
function normalizeFinding(finding) {
  return {
    severity: (finding.severity || "LOW").toUpperCase(),
    issue: finding.issue || finding.message || "Unknown issue",
    explanation: finding.explanation || finding.details || finding.message || "Generated by AI code review.",
    suggestedFix: finding.suggestedFix || finding.recommendation || "No automatic fix provided.",
    lineNumber: finding.lineNumber || finding.line || null,
  };
}

/**
 * Complete orchestrator sequence for analyzing code snippets
 */
async function reviewSnippet(projectId, language, code) {
  let review;
  let lintIssues = [];

  try {
    // 1. Create Initial Review Database Record (State: PROCESSING)
    review = await prisma.review.create({
      data: {
        projectId,
        sourceCode: code,
        overallScore: 0,
        summary: "Review is being processed...",
        aiModel: process.env.GEMINI_MODEL || "gemini-3.5-flash",
        status: "PROCESSING",
      },
    });

    // 2. Run Static Analysis / Linter
    switch (language) {
      case "JAVASCRIPT":
        lintIssues = await analyzeJavaScript(code);
        break;
      default:
        lintIssues = [];
    }

    // 3. Save Linter Issues if they exist
    if (lintIssues.length) {
      await prisma.staticIssue.createMany({
        data: lintIssues.map((issue) => ({
          reviewId: review.id,
          tool: "ESLint",
          severity: (issue.severity || "warning").toUpperCase(),
          message: issue.message,
          lineNumber: issue.line,
        })),
      });
    }

    // 4. Send Code and Lint insights downstream to Gemini 
    const aiReview = await reviewCode(code, language, lintIssues);

    // 5. Clean and Store AI Structural Findings
    const rawFindings = aiReview.findings || [];
    if (rawFindings.length) {
      const normalizedFindings = rawFindings.map(normalizeFinding);
      
      await prisma.reviewFinding.createMany({
        data: normalizedFindings.map((finding) => ({
          reviewId: review.id,
          ...finding,
        })),
      });
    }

    // 6. Build and Record Scoring/Maintainability Metrics
    await prisma.reviewMetric.create({
      data: {
        reviewId: review.id,
        complexity: aiReview.metrics?.complexity || 80, // Fallback if AI skips metric
        maintainability: aiReview.metrics?.maintainability || 75,
        securityScore: aiReview.metrics?.security || 75,
        performanceScore: aiReview.metrics?.performance || 75,
        readabilityScore: aiReview.metrics?.readability || 75,
      },
    });

    // 7. Update Main Record to Finish Pipeline (State: COMPLETED)
    const completedReview = await prisma.review.update({
      where: { id: review.id },
      data: {
        overallScore: aiReview.overallScore || 0,
        summary: aiReview.summary || "Code evaluation finalized.",
        status: "COMPLETED",
      },
    });

    return {
      reviewId: review.id,
      status: "COMPLETED",
      lintIssues,
      aiReview,
    };

  } catch (error) {
    console.error("Critical failure during review processing pipeline:", error);

    // Operational Safe Guard: Mark progress as FAILED if crash occurs after DB creation
    if (review?.id) {
      try {
        await prisma.review.update({
          where: { id: review.id },
          data: { status: "FAILED" },
        });
      } catch (dbError) {
        console.error("Could not update status to FAILED:", dbError);
      }
    }

    throw error;
  }
}

module.exports = {
  reviewSnippet,
};