const {
  analyzeJavaScript,
} = require("../lint/eslint.service");
const prisma = require("../../config/prisma");
const {
  reviewCode,
} = require("../ai/gemini.service");

async function reviewSnippet(projectId, language, code) {
  let lintIssues = [];

  switch (language) {
    case "JAVASCRIPT":
      lintIssues = await analyzeJavaScript(code);
      break;

    default:
      lintIssues = [];
  }

  const aiReview = await reviewCode(
    code,
    language,
    lintIssues
  );


  function normalizeSeverity(severity) {
  const value = (severity || "").toUpperCase();

  switch (value) {
    case "HIGH":
      return "HIGH";

    case "MEDIUM":
      return "MEDIUM";

    case "LOW":
      return "LOW";

    case "INFO":
    case "MINOR":
    case "STYLE":
    default:
      return "LOW";
  }
}

  const review = await prisma.review.create({
  data: {
    projectId,
    sourceCode: code,
    overallScore: aiReview.overallScore,
    summary: aiReview.summary,
    aiModel: process.env.GEMINI_MODEL || "gemini-3.5-flash",
  },
});

if (lintIssues.length) {
  await prisma.staticIssue.createMany({
    data: lintIssues.map((issue) => ({
      reviewId: review.id,
      tool: "ESLint",
      severity: issue.severity.toUpperCase(),
      message: issue.message,
      lineNumber: issue.line,
    })),
  });
}

const findings = aiReview.findings || [];

if (findings.length) {
  await prisma.reviewFinding.createMany({
    data: findings.map((finding) => ({
      reviewId: review.id,
      severity: (finding.severity || "LOW").toUpperCase(),

      issue: finding.issue || finding.message || "",

      explanation:
        finding.explanation ||
        "Generated by AI code review.",

      suggestedFix:
        finding.suggestedFix ||
        "No automatic fix provided.",

      lineNumber:
        finding.lineNumber ||
        finding.line ||
        null,
    })),
  });
}

await prisma.reviewMetric.create({
  data: {
    reviewId: review.id,

    complexity: 80,

    maintainability: aiReview.metrics.maintainability,

    securityScore: aiReview.metrics.security,

    performanceScore: aiReview.metrics.performance,

    readabilityScore: aiReview.metrics.readability,
  },
});

 return {
  reviewId: review.id,
  lintIssues,
  aiReview,
};
}

module.exports = {
  reviewSnippet,
};